### ISSUE TITLE
[ERROR]: Unexpected game code "Untitled"

### ISSUE THREAD

**Issue by iMrDJAi** [McCaulay/mast1c0re-ps2-network-game-loader#2]
I know this is most likely related to the `.iso` itself, can you give me some insight?
Are there PS2 `.iso`s with altered game code? And can this code be modified?

**Comment by McCaulay** [comment]
So to boot a PS2 game you need the game code of the ISO in a specific format. For example for Okage: Shadow King the boot string is `cdrom0:\SCUS_971.29;1`.

The network loader attempts to automatically retrieve this `SCUS-97129` game code by pulling it from EBOOT memory once the ISO has been mounted by the PlayStation emulator. You can see this being called (`PS::GetMountedGameCode`) in the following files:

https://github.com/McCaulay/mast1c0re-ps2-network-game-loader/blob/cf2829bdb54c7deb00df147ec1a46eec618ceef6/src/main.cpp#L39-L40

* https://github.com/McCaulay/mast1c0re/blob/5e6f2585ea0c988a50090f273bb6bbe17cdd1d74/sdk/include/offsets/ps/eboot/1.01.hpp#L16
* https://github.com/McCaulay/mast1c0re/blob/5e6f2585ea0c988a50090f273bb6bbe17cdd1d74/sdk/src/ps/ps.cpp#L192-L196

When the emulator cannot find the game code for an ISO, it sets the game code value to "Untitled" which is what causes this error to occur.

It may be possible to get the game to load in the emulator if you manually set the game code in the source code. For example, you could change the line from `char* gameCode = PS::GetMountedGameCode();` to `char* gameCode = "SCUS-97129";`

The function `PS2::gameCodeToPath` further on will convert the game code `SCUS-97129` to `cdrom0:\\SCUS_971.29;1` which is required to boot.

This boot string information can be found in the `SYSTEM.CNF` file located in the root directory of the ISO image. For example, this is the contents of the `SYSTEM.CNF` file for Okage: Shadow King

```
BOOT2 = cdrom0:\SCUS_971.29;1
VER = 1.01
VMODE = NTSC
```

**Comment by iMrDJAi** [comment]
@McCaulay I have noticed that this issue is happening with ROMS that come in `.bin` format, converting them to `.iso` format didn't help. The `SYSTEM.CNF` file does indeed include a valid boot string.
